// Generated by build.js from src/cmc.js - edit that, not this.
var __XCAP_EXTENSION = true;

/**
 * CoinMarketCap token capture.
 * Paste into the DevTools Console on a coinmarketcap.com page.
 *
 * CMC renders server-side, so the data is embedded in the page source rather
 * than fetched - nothing useful shows up in the Network tab. This reads the
 * JSON out of the page and lists one row per token contract, with copy buttons.
 */
(() => {
    // ─────────────────────────── CONFIG ───────────────────────────
    const CONFIG = {
        // Where the "Copy + Open Sheet" button goes.
        sheetUrl: '',

        // Open the sheet in this tab (true) or a new one (false).
        sheetSameTab: false,

        // Build the avatar URL from the id when the page does not carry one:
        //   https://s2.coinmarketcap.com/static/img/coins/64x64/<id>.png
        // An avatar the page does supply still wins over this.
        deriveAvatar: true,

        // A native coin has no chain and no contract, so both columns come
        // out empty and the row has nothing to key on in the sheet. This
        // stands the symbol in for the chain and UCID=<id> for the contract -
        // UCID being CMC's own name for that id, so the row still points at
        // something real. Set false to leave the columns empty instead.
        nativeAsUcid: true
    };
    // ──────────────────────────────────────────────────────────────

    // Installed as an extension, the settings live in chrome.storage, which a
    // MAIN-world script cannot reach - and MAIN world is required, since
    // hooking the page's own fetch is the whole point. bridge.js copies the
    // settings onto the root element instead, and signals when they change.
    function applyStoredConfig() {
        try {
            const raw = document.documentElement.getAttribute('data-xcap-config');
            if (raw) Object.assign(CONFIG, JSON.parse(raw));
        } catch (e) { /* keep the defaults above */ }
    }
    applyStoredConfig();

    // Re-pasting must replace the running build, not stack another set of
    // observers on top of it.
    if (window.__cmc) {
        if (!window.__cmc.uninstall) {
            console.warn('[cmc] an older build is running and cannot be removed - reload the page (F5), then paste again');
            return;
        }
        window.__cmc.uninstall();
        console.log('%c[cmc] replaced previous build', 'color:#666');
    }

    // CMC names the same three things two different ways depending on where
    // in the payload they appear, so each is looked up by either name.
    const ADDRESS_KEYS = ['tokenAddress', 'contractAddress'];
    const PLATFORM_ID_KEYS = ['platformId', 'contractPlatformId'];
    const PLATFORM_NAME_KEYS = ['platformName', 'contractPlatform'];

    // Scanning only for an address misses native coins entirely - BTC has no
    // contract - so currency records are searched for by their own field too.
    const NEEDLES = ADDRESS_KEYS.concat(['slug']);
    const MAX_OBJ = 400000;       // longest object worth trying to parse
    const MAX_HITS = 4000;

    const MONO = 'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
    const SANS = '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif';

    const CSS_PANEL = 'position:fixed;top:16px;right:16px;z-index:2147483647;width:460px;'
        + 'max-height:82vh;overflow:auto;background:#fff;color:#000;border:2px solid #000;'
        + 'box-shadow:0 8px 32px rgba(0,0,0,.35);font-family:' + SANS + ';font-size:12px;'
        + 'text-align:left;box-sizing:border-box;';
    const CSS_HEAD = 'display:flex;align-items:center;justify-content:space-between;gap:8px;'
        + 'padding:10px 12px;background:#000;color:#fff;cursor:move;position:sticky;top:0;'
        + 'font-size:11px;font-weight:700;letter-spacing:.5px;text-transform:uppercase;';
    const CSS_BTN = 'display:inline-block;padding:5px 10px;background:#000;color:#fff;'
        + 'border:1px solid #000;border-radius:0;font-family:' + SANS + ';font-size:10px;'
        + 'font-weight:700;letter-spacing:.5px;text-transform:uppercase;cursor:pointer;'
        + 'line-height:1;margin:0;box-sizing:border-box;';

    // One definition drives the column headings, the TSV and the JSON, so
    // the three cannot fall out of order with each other.
    const FIELDS = [
        ['Avatar', 'avatar'],
        ['Symbol', 'symbol'],
        ['Slug', 'slug'],
        ['ID', 'id'],
        ['PlatformID', 'platformId'],
        ['PlatformName', 'platformName'],
        ['TokenAddress', 'tokenAddress']
    ];
    const COLUMNS = FIELDS.map(f => f[0]);

    const found = new Map();          // address -> Map(platformId -> row)
    const nativeCoins = new Map();    // id -> row, for coins that have no contract
    const avatarById = new Map();     // every avatar seen, indexed for later
    const avatarBySymbol = new Map();
    const sources = [];               // where each batch came from, for debugging
    let rawHits = [];                 // every object carrying the key, unprocessed
    let timer = null;
    let minimized = false;
    let onlyCurrent = true;
    let query = '';

    // ---- reading the page ----------------------------------------------

    const isStr = v => typeof v === 'string' && v.trim() !== '';
    const str = v => (isStr(v) ? v.trim() : '');
    const num = v => {
        const n = typeof v === 'number' ? v : (isStr(v) ? Number(v) : NaN);
        return isFinite(n) ? n : null;
    };

    // first of the alternative names that the object actually carries
    const pickStr = (o, keys) => {
        for (const k of keys) if (isStr(o[k])) return str(o[k]);
        return '';
    };
    const pickNum = (o, keys) => {
        for (const k of keys) {
            const n = num(o[k]);
            if (n != null) return n;
        }
        return null;
    };
    const addressOf = o => (o && typeof o === 'object' && !Array.isArray(o)
        ? pickStr(o, ADDRESS_KEYS) : '');

    // Positions of every occurrence, so the brace scanner can ask "does any
    // occurrence fall inside this object?" without re-scanning the slice -
    // the difference between linear and quadratic on a page this size.
    function positionsOf(text, needle) {
        const at = [];
        let i = -1;
        while ((i = text.indexOf(needle, i + 1)) !== -1) {
            at.push(i);
            if (at.length > MAX_HITS) break;
        }
        return at;
    }

    function anyInRange(sorted, lo, hi) {
        let a = 0, b = sorted.length - 1;
        while (a <= b) {
            const mid = (a + b) >> 1;
            if (sorted[mid] < lo) a = mid + 1;
            else if (sorted[mid] > hi) b = mid - 1;
            else return true;
        }
        return false;
    }

    // Every JSON object in the text that contains the key. Objects close
    // innermost-first, so a contract record arrives before the coin object
    // wrapping it, and both are kept - one names the contract, the other
    // carries the symbol.
    function scanObjects(text, needleKey) {
        const needle = '"' + needleKey + '"';
        const at = positionsOf(text, needle);
        if (!at.length) return [];

        const out = [];
        const stack = [];
        let inStr = false, esc = false;

        for (let i = 0; i < text.length; i++) {
            const c = text[i];
            if (inStr) {
                if (esc) esc = false;
                else if (c === '\\') esc = true;
                else if (c === '"') inStr = false;
                continue;
            }
            if (c === '"') { inStr = true; continue; }
            if (c === '{') { stack.push(i); continue; }
            if (c !== '}') continue;

            const start = stack.pop();
            if (start === undefined) continue;
            if (i - start > MAX_OBJ) continue;
            if (!anyInRange(at, start, i)) continue;
            try {
                const o = JSON.parse(text.slice(start, i + 1));
                if (o && typeof o === 'object') out.push(o);
            } catch (e) { /* a fragment, not a whole object */ }
            if (out.length > 2000) break;
        }
        return out;
    }

    // App Router ships its payload inside JS string literals, so the key only
    // ever appears escaped. Each literal is pulled out and decoded properly:
    // a blanket replace of \" leaves every quote ambiguous, and the brace
    // scanner then reads the payload's opening { as part of a string and
    // finds nothing at all.
    function decodedLiterals(text) {
        const needles = NEEDLES.map(n => '\\"' + n + '\\"');
        if (!needles.some(n => text.indexOf(n) !== -1)) return [];

        const out = [];
        for (let i = 0; i < text.length; i++) {
            if (text[i] !== '"') continue;
            let j = i + 1, esc = false;
            for (; j < text.length; j++) {
                const c = text[j];
                if (esc) { esc = false; continue; }
                if (c === '\\') { esc = true; continue; }
                if (c === '"') break;
            }
            if (j >= text.length) break;
            const literal = text.slice(i, j + 1);
            i = j;
            if (!needles.some(n => literal.indexOf(n) !== -1)) continue;
            try {
                const decoded = JSON.parse(literal);
                if (typeof decoded === 'string') out.push(decoded);
            } catch (e) { /* not a JSON-compatible literal */ }
            if (out.length > 60) break;
        }
        return out;
    }

    // Payloads are occasionally encoded twice over, so decoding repeats while
    // a key is still escaped.
    function textVariants(text) {
        const out = [text];
        let round = [text];
        for (let depth = 0; depth < 2 && round.length; depth++) {
            const next = [];
            round.forEach(t => decodedLiterals(t).forEach(d => { out.push(d); next.push(d); }));
            round = next;
        }
        return out;
    }

    function harvestText(text, label) {
        if (!text || text.length < 20) return 0;
        let n = 0;
        textVariants(text).forEach(v => {
            NEEDLES.forEach(needle => {
                scanObjects(v, needle).forEach(o => { n += absorb(o); });
            });
        });
        if (n) sources.push(label + ' (' + n + ')');
        return n;
    }

    function harvestTree(root, label) {
        const n = absorb(root);
        if (n) sources.push(label + ' (' + n + ')');
        return n;
    }

    function clearAll() {
        found.clear();
        nativeCoins.clear();
        avatarById.clear();
        avatarBySymbol.clear();
        rawHits = [];
        sources.length = 0;
    }

    function scan() {
        sources.length = 0;
        rawHits = [];

        // 1. objects already parsed and hanging off window
        ['__NEXT_DATA__', '__APP_STATE__', '__INITIAL_STATE__', '__NUXT__'].forEach(k => {
            try { if (window[k] && typeof window[k] === 'object') harvestTree(window[k], 'window.' + k); }
            catch (e) { /* getter threw */ }
        });

        // 2. the App Router's streamed chunks
        try {
            const f = self.__next_f;
            if (Array.isArray(f)) {
                const joined = f.map(chunk => (Array.isArray(chunk)
                    ? chunk.map(x => (typeof x === 'string' ? x : '')).join('')
                    : (typeof chunk === 'string' ? chunk : ''))).join('');
                harvestText(joined, '__next_f');
            }
        } catch (e) { /* not App Router */ }

        // 3. every inline script, which covers __NEXT_DATA__ and any
        //    application/json blob without needing to know their names
        try {
            document.querySelectorAll('script').forEach((s, i) => {
                if (s.src) return;
                harvestText(s.textContent, s.id ? '#' + s.id : 'script[' + i + ']');
            });
        } catch (e) { /* document not ready */ }

        // not forced: running on every page it matches, the panel has to earn
        // its place by finding something. The caller forces it when a person
        // asked for it directly.
        render(false);
        return list().length;
    }

    // ---- turning objects into rows --------------------------------------

    // Only the node's own avatar. Searching deeper would happily attach some
    // unrelated image further down the tree to a contract row.
    function ownAvatar(node) {
        if (!node || typeof node !== 'object') return '';
        if (node.avatar && isStr(node.avatar.url)) return node.avatar.url;
        if (isStr(node.avatar)) return node.avatar;
        return '';
    }

    // Own field wins; the wrapping coin object only fills what the contract
    // record leaves blank.
    function rowOf(contract, coin) {
        const own = (a, b) => (a !== '' && a != null ? a : b);
        return {
            avatar: own(ownAvatar(contract), coin ? ownAvatar(coin) : ''),
            symbol: own(str(contract.symbol), coin ? str(coin.symbol) : ''),
            slug: own(str(contract.slug), coin ? str(coin.slug) : ''),
            id: own(num(contract.id), coin ? num(coin.id) : null),
            platformId: pickNum(contract, PLATFORM_ID_KEYS),
            platformName: pickStr(contract, PLATFORM_NAME_KEYS),
            tokenAddress: addressOf(contract)
        };
    }

    // Rows are filed by address, then by chain within it. The same address
    // really can exist on several chains - an EVM contract deployed from the
    // same account and nonce lands on the same address everywhere - so those
    // stay separate. A sighting that never named a chain is filed under null
    // and folded away later, once a sighting that did name one turns up.
    function keep(row) {
        if (!row.tokenAddress) return false;

        const address = row.tokenAddress.toLowerCase();
        let byChain = found.get(address);
        if (!byChain) { byChain = new Map(); found.set(address, byChain); }

        const chain = row.platformId == null ? null : row.platformId;
        const prev = byChain.get(chain);
        byChain.set(chain, prev ? merge(prev, row) : row);
        return !prev;
    }

    // Neither sighting is wholly better than the other - one may name the
    // chain while the other carries the avatar - so take the best of each.
    function merge(a, b) {
        return {
            avatar: a.avatar || b.avatar,
            symbol: a.symbol || b.symbol,
            slug: a.slug || b.slug,
            id: a.id != null ? a.id : b.id,
            platformId: a.platformId != null ? a.platformId : b.platformId,
            platformName: a.platformName || b.platformName,
            tokenAddress: a.tokenAddress || b.tokenAddress
        };
    }

    // A contract record usually carries no symbol of its own - that sits on
    // the coin object wrapping it, which may be several levels up past a
    // "platforms" array. Descending breadth-first carries the nearest
    // enclosing coin down to each contract.
    // A currency record proper, rather than any object that happens to carry a
    // symbol. slug and category are CMC's own fields, so requiring one of them
    // keeps unrelated wrappers out.
    const isCurrencyRecord = n => isStr(n.symbol) && num(n.id) != null
        && (isStr(n.slug) || isStr(n.category));

    function absorb(root) {
        if (!root || typeof root !== 'object') return 0;

        let added = 0;
        const queue = [{ node: root, coin: null }];
        let steps = 0;

        // A native coin - BTC and the like - has no contract anywhere, so
        // keying everything off tokenAddress made it invisible. Currency
        // records are noted as they go past, and the ones that turn out to
        // own no contract become rows of their own.
        const currencies = new Set();
        const withContract = new Set();

        while (queue.length && steps++ < 200000) {
            const item = queue.shift();
            const node = item.node;
            if (!node || typeof node !== 'object') continue;

            // a symbol is what marks an object as the coin, rather than an id,
            // which all sorts of unrelated wrappers also carry
            const isCoin = !Array.isArray(node) && isStr(node.symbol);
            const coin = isCoin ? node : item.coin;

            // index every avatar against whatever names it, wherever it sits
            if (!Array.isArray(node)) {
                const url = ownAvatar(node);
                if (url) {
                    const id = num(node.id);
                    if (id != null && !avatarById.has(id)) avatarById.set(id, url);
                    const symbol = str(node.symbol);
                    if (symbol && !avatarBySymbol.has(symbol)) avatarBySymbol.set(symbol, url);
                }
            }

            if (!Array.isArray(node) && isCurrencyRecord(node)) currencies.add(node);

            if (addressOf(node)) {
                if (rawHits.length < 500) rawHits.push(node);
                if (keep(rowOf(node, coin === node ? item.coin : coin))) added++;
                if (coin) withContract.add(coin);
                if (isCurrencyRecord(node)) withContract.add(node);
            }

            const keys = Array.isArray(node) ? node.keys() : Object.keys(node);
            for (const k of keys) {
                let v;
                try { v = node[k]; } catch (e) { continue; }
                if (v && typeof v === 'object') queue.push({ node: v, coin });
            }
        }

        currencies.forEach(c => { if (!withContract.has(c)) added += keepNative(c); });
        return added;
    }

    function keepNative(node) {
        const id = num(node.id);
        if (id == null) return 0;
        const row = {
            avatar: ownAvatar(node),
            symbol: str(node.symbol),
            slug: str(node.slug),
            id: id,
            platformId: null,
            platformName: '',
            tokenAddress: ''
        };
        const prev = nativeCoins.get(id);
        nativeCoins.set(id, prev ? merge(prev, row) : row);
        return prev ? 0 : 1;
    }

    // What a typed query is matched against, and the shorthands accepted for
    // each field.
    const QUERY_ALIASES = {
        sym: 'symbol', ticker: 'symbol', name: 'symbol',
        s: 'slug',
        ucid: 'id', cid: 'id',
        chain: 'chain', platform: 'chain', net: 'chain',
        pid: 'platformid',
        addr: 'contract', address: 'contract', ca: 'contract'
    };

    // an id is a number, not a piece of text: "1" should find Bitcoin, not
    // every id that happens to contain a 1
    const QUERY_EXACT = { id: true, platformid: true };

    const searchFields = r => ({
        symbol: (r.symbol || '').toLowerCase(),
        slug: (r.slug || '').toLowerCase(),
        id: r.id == null ? '' : String(r.id),
        chain: (r.platformName || '').toLowerCase(),
        platformid: r.platformId == null ? '' : String(r.platformId),
        contract: (r.tokenAddress || '').toLowerCase()
    });

    // /currencies/bitcoin/ -> bitcoin. Anything else - a listing, the front
    // page - has no one coin to filter to.
    function pageSlug() {
        const m = location.pathname.match(/\/currencies\/([^\/?#]+)/i);
        return m ? decodeURIComponent(m[1]).toLowerCase() : '';
    }

    // A coin page embeds every coin in its sidebars and tables too, so the
    // page's own slug is what separates the one being looked at from the
    // scenery around it.
    function list() {
        return applyQuery(onPage());
    }

    function onPage() {
        const all = listAll();
        if (!onlyCurrent) return all;
        const slug = pageSlug();
        if (!slug) return all;
        const mine = all.filter(r => r.slug && r.slug.toLowerCase() === slug);
        // showing nothing would read as a broken scan rather than a filter
        return mine.length ? mine : all;
    }

    function applyQuery(rows) {
        const match = makeMatcher(query, QUERY_ALIASES, QUERY_EXACT);
        return match ? rows.filter(r => match(searchFields(r))) : rows;
    }

    function filterState() {
        const slug = pageSlug();
        if (!onlyCurrent || !slug) return { active: false, slug: slug, matched: 0 };
        const matched = listAll().filter(r => r.slug && r.slug.toLowerCase() === slug).length;
        return { active: matched > 0, slug: slug, matched: matched };
    }

    function listAll() {
        const out = [];
        found.forEach(byChain => {
            const named = [...byChain.entries()].filter(([chain]) => chain !== null);
            const chainless = byChain.get(null);
            if (named.length) {
                // the chainless sighting was the same contract seen without its
                // chain, so its fields belong to the named rows, not to a row
                // of its own
                named.forEach(([, row]) => out.push(chainless ? merge(row, chainless) : row));
            } else if (chainless) {
                out.push(chainless);
            }
        });

        // A coin whose contract was found elsewhere in the page is already
        // here; only the ones with no contract row at all are still missing.
        const covered = new Set(out.map(r => r.id).filter(v => v != null));
        nativeCoins.forEach((row, id) => { if (!covered.has(id)) out.push(row); });

        return out.map(withAvatar).map(withNativeIdentity).sort((a, b) =>
            (a.symbol || '').localeCompare(b.symbol || '')
            || ((a.platformId || 0) - (b.platformId || 0)));
    }

    // Applied on the way out rather than on the way in, so what was actually
    // read off the page stays distinguishable from what was filled in for it.
    function withNativeIdentity(row) {
        if (!CONFIG.nativeAsUcid || row.tokenAddress || row.id == null) return row;
        return Object.assign({}, row, {
            platformName: row.platformName || row.symbol,
            tokenAddress: 'UCID=' + row.id
        });
    }

    // The avatar sits on the coin's own object, which is not always an
    // ancestor of the contract record - on a coin page it is off to one side
    // entirely. So every avatar seen anywhere is indexed by id and symbol, and
    // rows that came through without one are matched up afterwards.
    function withAvatar(row) {
        if (row.avatar) return row;
        let url = (row.id != null && avatarById.get(row.id))
            || (row.symbol && avatarBySymbol.get(row.symbol)) || '';
        if (!url && CONFIG.deriveAvatar && row.id != null) {
            url = 'https://s2.coinmarketcap.com/static/img/coins/64x64/' + row.id + '.png';
        }
        return url ? Object.assign({}, row, { avatar: url }) : row;
    }

    // JSON says null for a missing value, TSV leaves the cell empty.
    const jsonOf = r => JSON.stringify(Object.fromEntries(
        FIELDS.map(([, key]) => [key, r[key] === '' || r[key] === undefined ? null : r[key]])
    ), null, 2);

    const tsvOf = r => FIELDS
        .map(([, key]) => (r[key] == null ? '' : String(r[key])))
        .join('\t');

    // ---- ui kit ------------------------------------------------------------
    //
    // Shared by both capture scripts; build.js splices this in where each one
    // says @@UI_KIT@@, so the two panels cannot drift apart visually.
    //
    // Icons are Lucide (ISC licence), inlined as path data. They cannot be
    // imported: MV3 forbids remote code, and a content script drawing into the
    // page is bound by that page's CSP either way, so a CDN link or a sprite
    // sheet would simply fail to load.

    const ICONS = {
        grip: '<circle cx="9" cy="6" r="1"/><circle cx="15" cy="6" r="1"/>'
            + '<circle cx="9" cy="12" r="1"/><circle cx="15" cy="12" r="1"/>'
            + '<circle cx="9" cy="18" r="1"/><circle cx="15" cy="18" r="1"/>',
        copy: '<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/>'
            + '<path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>',
        check: '<path d="M20 6 9 17l-5-5"/>',
        x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
        minus: '<path d="M5 12h14"/>',
        plus: '<path d="M5 12h14"/><path d="M12 5v14"/>',
        refresh: '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/>'
            + '<path d="M21 3v5h-5"/>'
            + '<path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/>'
            + '<path d="M3 21v-5h5"/>',
        filter: '<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>',
        layers: '<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/>'
            + '<path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65"/>'
            + '<path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65"/>',
        sheet: '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/>'
            + '<line x1="3" x2="21" y1="9" y2="9"/><line x1="3" x2="21" y1="15" y2="15"/>'
            + '<line x1="9" x2="9" y1="9" y2="21"/><line x1="15" x2="15" y1="9" y2="21"/>',
        braces: '<path d="M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1"/>'
            + '<path d="M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1"/>',
        trash: '<path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/>'
            + '<path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>',
        link: '<path d="M15 3h6v6"/><path d="M10 14 21 3"/>'
            + '<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
        alert: '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/>'
            + '<path d="M12 9v4"/><path d="M12 17h.01"/>',
        search: '<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',
        scan: '<path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/>'
            + '<path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/>'
            + '<path d="M7 12h10"/>'
    };

    const SVG_NS = 'http://www.w3.org/2000/svg';

    function icon(name, size) {
        const svg = document.createElementNS(SVG_NS, 'svg');
        svg.setAttribute('viewBox', '0 0 24 24');
        svg.setAttribute('width', size || 14);
        svg.setAttribute('height', size || 14);
        svg.setAttribute('fill', 'none');
        svg.setAttribute('stroke', 'currentColor');
        svg.setAttribute('stroke-width', '2');
        svg.setAttribute('stroke-linecap', 'round');
        svg.setAttribute('stroke-linejoin', 'round');
        svg.setAttribute('aria-hidden', 'true');
        svg.innerHTML = ICONS[name] || '';
        return svg;
    }

    // The panel lives in a shadow root, so the host page's stylesheets cannot
    // reach it and this can be a real stylesheet rather than inline styles on
    // every element.
    const THEME = `
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    .panel {
        --sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
        --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
        --bg: #0a0a0a;
        --bg-head: #0a0a0a;
        --bg-sub: #141414;
        --line: #2a2a2c;
        --line-soft: #2a2a2c;
        --fg: #f4f4f5;
        --fg-dim: #8b8b90;
        --fg-faint: #636369;
        font-family: var(--sans);
        font-size: 13px;
        line-height: 1.5;
        color: var(--fg);
        background: var(--bg);
        border: none;
        border-radius: 24px;
        box-shadow: 0 0 0 1px rgba(255,255,255,.08), 0 24px 64px rgba(0,0,0,.55);
        display: flex;
        flex-direction: column;
        max-height: 84vh;
        overflow: hidden;
    }
    .head {
        display: flex; align-items: center; gap: 8px;
        padding: 9px 10px;
        background: var(--bg-head);
        border-bottom: 1px solid var(--line);
        cursor: grab; user-select: none; flex: 0 0 auto;
    }
    .head:active { cursor: grabbing; }
    .head .grip { color: var(--fg-faint); flex: 0 0 auto; display: flex; }
    .title {
        font-size: 13px; font-weight: 500; letter-spacing: 0; text-transform: none;
        color: var(--fg); white-space: nowrap;
    }
    .count {
        font-size: 12px; color: var(--fg-dim);
        padding: 0; min-width: 0; text-align: left; border: none;
    }
    .spacer { flex: 1 1 auto; }
    .tools { display: flex; gap: 4px; flex: 0 0 auto; }

    button {
        font-family: var(--sans); font-size: 13px; color: inherit;
        background: none; border: 1px solid transparent; border-radius: 999px;
        cursor: pointer; display: inline-flex; align-items: center; justify-content: center;
    }
    .ibtn {
        width: 36px; height: 36px; color: var(--fg-dim);
        border-color: transparent; transition: color .12s, background .12s;
    }
    .ibtn:hover { color: var(--fg); background: #1c1c1c; }
    .ibtn.on { color: #0a0a0a; background: var(--fg); }

    .strip {
        display: flex; align-items: center; gap: 6px;
        padding: 6px 10px; background: var(--bg-sub);
        border-bottom: 1px solid var(--line-soft);
        font-size: 11px; color: var(--fg-dim); flex: 0 0 auto;
    }
    .strip .k { color: var(--fg); }
    .strip svg { flex: 0 0 auto; color: var(--fg-faint); }

    .search {
        display: flex; align-items: center; gap: 8px;
        margin: 8px 10px; padding: 0 12px; height: 40px; flex: 0 0 auto;
        background: #141414; border: none; border-radius: 999px;
        box-shadow: 0 0 0 1px rgba(255,255,255,.08);
    }
    .search svg { color: var(--fg-faint); flex: 0 0 auto; }
    .search input {
        flex: 1 1 auto; min-width: 0; height: 100%;
        background: none; border: none; outline: none;
        font-family: var(--sans); font-size: 13px; color: var(--fg);
    }
    .search input::placeholder { color: var(--fg-faint); }
    .search .hits {
        flex: 0 0 auto; font-size: 10px; color: var(--fg-faint);
        font-variant-numeric: tabular-nums;
    }
    .search .clear {
        flex: 0 0 auto; width: 20px; height: 20px; color: var(--fg-faint);
    }
    .search .clear:hover { color: var(--fg); }
    .search:focus-within { background: #0f0f13; }
    .search:focus-within svg { color: var(--fg-dim); }

    .body { overflow: auto; flex: 1 1 auto; }
    .body::-webkit-scrollbar { width: 10px; height: 10px; }
    .body::-webkit-scrollbar-thumb { background: #26262b; border: 3px solid var(--bg); }
    .body::-webkit-scrollbar-track { background: var(--bg); }

    table { width: 100%; border-collapse: collapse; }
    thead th {
        position: sticky; top: 0; z-index: 1;
        background: var(--bg-sub);
        padding: 6px 10px; text-align: left;
        font-size: 11px; font-weight: 500; letter-spacing: 0; text-transform: none;
        color: var(--fg-dim);
        border-bottom: 1px solid var(--line);
        white-space: nowrap;
    }
    tbody td {
        padding: 8px 10px; vertical-align: middle;
        border-bottom: 1px solid var(--line-soft);
        font-size: 12px;
    }
    tbody tr:hover td { background: #141418; }
    tbody tr:last-child td { border-bottom: none; }
    td.num { text-align: right; color: var(--fg-dim); font-variant-numeric: tabular-nums; }
    td.act { width: 34px; text-align: right; padding-left: 0; }

    .token { display: flex; align-items: center; gap: 8px; min-width: 0; }
    .token img {
        width: 18px; height: 18px; border-radius: 50%;
        background: #1a1a1e; flex: 0 0 auto;
    }
    .token .names { min-width: 0; overflow: hidden; }
    .token .sym { font-weight: 700; letter-spacing: .02em; white-space: nowrap; }
    .token .sub {
        font-size: 10px; color: var(--fg-faint); letter-spacing: .04em;
        white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
    }
    tbody td:first-child { min-width: 132px; }
    .clip { display: block; max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: var(--mono); font-size: 11px; }
    .dim { color: var(--fg-dim); }
    .faint { color: var(--fg-faint); }

    .rows { padding: 2px 0; }
    .field { padding: 8px 10px; border-bottom: 1px solid var(--line-soft); }
    .field .lab {
        display: flex; align-items: center; justify-content: space-between; gap: 8px;
        font-size: 11px; letter-spacing: 0; text-transform: none; color: var(--fg-dim);
        margin-bottom: 5px;
    }
    .field .val {
        background: #141414; border: none; border-radius: 12px;
        padding: 8px 10px; font-size: 11px; line-height: 1.55;
        font-family: var(--mono);
        word-break: break-all; max-height: 72px; overflow: auto; color: var(--fg);
        box-shadow: 0 0 0 1px rgba(255,255,255,.08);
    }
    .kv { display: flex; gap: 10px; padding: 4px 0; font-size: 12px; align-items: flex-start; }
    .kv .k { flex: 0 0 72px; color: var(--fg-dim); padding-top: 1px; }
    .kv .v { flex: 1 1 auto; word-break: break-all; font-family: var(--mono); font-size: 11px; }

    .foot {
        flex: 0 0 auto; border-top: 1px solid var(--line);
        background: #141414; padding: 10px; display: flex; flex-direction: column; gap: 6px;
    }
    .bar { display: flex; gap: 6px; }
    .tbtn {
        flex: 1 1 0; gap: 6px; height: 36px; padding: 0 12px;
        border-color: transparent; color: var(--fg); background: #1c1c1c;
        letter-spacing: 0; text-transform: none; font-size: 13px; font-weight: 500;
        transition: color .12s, background .12s;
        box-shadow: 0 0 0 1px rgba(255,255,255,.08);
    }
    .tbtn:hover { color: var(--fg); background: #242424; }
    .tbtn.primary { background: var(--fg); color: #0a0a0a; box-shadow: none; }
    .tbtn.primary:hover { background: #fff; }
    .tbtn.narrow { flex: 0 0 auto; width: 36px; padding: 0; }
    .tbtn.ok { color: #0a0a0a; background: var(--fg); }

    .hint { padding: 8px 10px 10px; font-size: 10px; line-height: 1.7; color: var(--fg-faint); }
    .empty {
        padding: 22px 16px; text-align: center; color: var(--fg-dim);
        font-size: 12px; line-height: 1.7;
    }
    .empty svg { color: var(--fg-faint); margin-bottom: 8px; }
    `;

    // One host element carrying a shadow root. Returned on later calls so the
    // panel keeps its position across re-renders.
    function shell(id, width) {
        const existing = document.getElementById(id);
        if (existing && existing.__ui) return existing.__ui;

        const host = document.createElement('div');
        host.id = id;
        host.style.cssText = 'position:fixed;top:16px;right:16px;z-index:2147483647;'
            + 'width:' + (width || 460) + 'px;max-width:calc(100vw - 32px);';

        const root = host.attachShadow({ mode: 'open' });
        const style = document.createElement('style');
        style.textContent = THEME;
        root.appendChild(style);

        const panel = document.createElement('div');
        panel.className = 'panel';
        root.appendChild(panel);

        host.__ui = { host: host, root: root, panel: panel };
        document.documentElement.appendChild(host);
        return host.__ui;
    }

    function el(tag, cls, text) {
        const n = document.createElement(tag);
        if (cls) n.className = cls;
        if (text != null) n.textContent = text;
        return n;
    }

    function iconBtn(name, title, fn, extraClass) {
        const b = el('button', 'ibtn' + (extraClass ? ' ' + extraClass : ''));
        b.title = title;
        b.appendChild(icon(name, 14));
        b.onclick = e => { e.stopPropagation(); fn(); };
        return b;
    }

    function textBtn(label, iconName, title, fn, extraClass) {
        const b = el('button', 'tbtn' + (extraClass ? ' ' + extraClass : ''));
        if (title) b.title = title;
        if (iconName) b.appendChild(icon(iconName, 13));
        const span = el('span', null, label);
        b.appendChild(span);
        b.__label = span;
        b.__icon = iconName;
        b.onclick = e => { e.stopPropagation(); fn(b); };
        return b;
    }

    // Swaps the label and icon for a moment, then puts them back.
    function feedback(button, text, iconName, ok) {
        if (!button || !button.__label) return;
        const label = button.__label.textContent;
        const original = button.__icon;
        button.__label.textContent = text;
        if (button.firstChild && button.firstChild.tagName === 'svg') {
            button.replaceChild(icon(iconName, 13), button.firstChild);
        }
        button.classList.toggle('ok', !!ok);
        setTimeout(() => {
            button.__label.textContent = label;
            if (original && button.firstChild && button.firstChild.tagName === 'svg') {
                button.replaceChild(icon(original, 13), button.firstChild);
            }
            button.classList.remove('ok');
        }, 1400);
    }

    function emptyState(iconName, text) {
        const wrap = el('div', 'empty');
        wrap.appendChild(icon(iconName, 22));
        wrap.appendChild(el('div', null, text));
        return wrap;
    }

    // ---- query -------------------------------------------------------------
    //
    // Plain words match any field; field:value narrows to one. Several terms all
    // have to match, so "sol usdc" and "chain:solana pump" both work.

    function parseQuery(text) {
        return String(text || '').trim().toLowerCase().split(/\s+/)
            .filter(Boolean)
            .map(term => {
                const colon = term.indexOf(':');
                return colon > 0
                    ? { key: term.slice(0, colon), value: term.slice(colon + 1) }
                    : { key: null, value: term };
            })
            .filter(term => term.value);
    }

    // aliases maps what a person might type to the field name the row uses.
    // exact names the fields where a digits-only term means that exact number:
    // substring matching on an id makes "ucid:1" match 1041 as well as 1.
    function makeMatcher(text, aliases, exact) {
        const terms = parseQuery(text);
        if (!terms.length) return null;
        const exactly = exact || {};

        const hit = (key, value, fields) => {
            const field = fields[key];
            if (field == null) return false;
            if (exactly[key] && /^\d+$/.test(value)) return field === value;
            return field.indexOf(value) !== -1;
        };

        return fields => terms.every(term => {
            if (!term.key) {
                for (const key in fields) if (hit(key, term.value, fields)) return true;
                return false;
            }
            const key = aliases[term.key] || term.key;
            // an unknown field name would otherwise match everything
            if (!(key in fields)) return false;
            return hit(key, term.value, fields);
        });
    }

    // The input is kept alive across row repaints - rebuilding it would take the
    // caret with it on every keystroke.
    function searchBox(state, onChange) {
        const wrap = el('div', 'search');
        wrap.appendChild(icon('search', 13));

        const input = document.createElement('input');
        input.type = 'text';
        input.value = state.query || '';
        input.placeholder = state.placeholder || 'filter…';
        input.spellcheck = false;
        input.addEventListener('input', () => onChange(input.value));
        input.addEventListener('keydown', e => {
            e.stopPropagation();   // the host page has its own shortcuts
            if (e.key === 'Escape' && input.value) { input.value = ''; onChange(''); }
        });
        wrap.appendChild(input);

        const hits = el('span', 'hits');
        wrap.appendChild(hits);

        const clear = iconBtn('x', 'Clear the filter', () => {
            input.value = '';
            onChange('');
            input.focus();
        }, 'clear');
        wrap.appendChild(clear);

        return {
            el: wrap,
            input: input,
            // shown only while filtering, so an unfiltered panel stays quiet
            update: (shown, total) => {
                const filtering = !!input.value;
                hits.textContent = filtering ? shown + '/' + total : '';
                clear.style.visibility = filtering ? 'visible' : 'hidden';
            }
        };
    }

    // ---- clipboard ---------------------------------------------------------

    function writeClipboard(text) {
        if (navigator.clipboard && navigator.clipboard.writeText) {
            return navigator.clipboard.writeText(text).catch(() => execCopy(text));
        }
        return execCopy(text);
    }

    // Covers browsers without the async API, and the "document is not focused"
    // rejection that follows focus moving to a newly opened tab.
    function execCopy(text) {
        return new Promise((resolve, reject) => {
            const ta = document.createElement('textarea');
            ta.value = text;
            ta.style.cssText = 'position:fixed;top:-2000px;left:-2000px;opacity:0';
            document.body.appendChild(ta);
            ta.select();
            let ok = false;
            try { ok = document.execCommand('copy'); } catch (e) { ok = false; }
            ta.remove();
            if (ok) resolve(); else reject(new Error('copy failed'));
        });
    }

    function copyBtn(label, iconName, title, getText, extraClass) {
        return textBtn(label, iconName, title, button => {
            writeClipboard(getText()).then(
                () => feedback(button, 'Copied', 'check', true),
                () => feedback(button, 'Failed', 'alert', false)
            );
        }, extraClass);
    }

    function copyIconBtn(title, getText) {
        const b = iconBtn('copy', title, () => {
            writeClipboard(getText()).then(() => {
                b.replaceChild(icon('check', 14), b.firstChild);
                b.classList.add('on');
                setTimeout(() => {
                    b.replaceChild(icon('copy', 14), b.firstChild);
                    b.classList.remove('on');
                }, 1200);
            }, () => {
                b.replaceChild(icon('alert', 14), b.firstChild);
                setTimeout(() => b.replaceChild(icon('copy', 14), b.firstChild), 1400);
            });
        });
        return b;
    }

    // Dragging moves the host, which is what carries the fixed position.
    function draggable(handle, host) {
        handle.onmousedown = e => {
            if (e.target.closest('button')) return;
            e.preventDefault();
            const r = host.getBoundingClientRect();
            const dx = e.clientX - r.left;
            const dy = e.clientY - r.top;
            const move = ev => {
                host.style.left = (ev.clientX - dx) + 'px';
                host.style.top = (ev.clientY - dy) + 'px';
                host.style.right = 'auto';
            };
            const up = () => {
                document.removeEventListener('mousemove', move);
                document.removeEventListener('mouseup', up);
            };
            document.addEventListener('mousemove', move);
            document.addEventListener('mouseup', up);
        };
    }

    function header(ui, title, count, tools) {
        const head = el('div', 'head');
        const grip = el('span', 'grip');
        grip.appendChild(icon('grip', 14));
        head.appendChild(grip);
        head.appendChild(el('span', 'title', title));
        head.appendChild(el('span', 'count', String(count)));
        head.appendChild(el('span', 'spacer'));
        const box = el('span', 'tools');
        tools.forEach(t => box.appendChild(t));
        head.appendChild(box);
        draggable(head, ui.host);
        return head;
    }


    // ---- sheet ----------------------------------------------------------

    function openSheet() {
        if (!CONFIG.sheetUrl) {
            console.warn('[cmc] no sheetUrl set - open the extension popup, or edit CONFIG above');
            return;
        }
        if (CONFIG.sheetSameTab) location.href = CONFIG.sheetUrl;
        else window.open(CONFIG.sheetUrl, '_blank', 'noopener');
    }

    // One click, both jobs. Order matters twice over: a popup blocker rejects
    // window.open once an await has broken the chain back to the click, and
    // navigating this tab away cancels a copy still in flight.
    function copyAndOpenSheet(text, button) {
        const done = writeClipboard(text);
        if (CONFIG.sheetSameTab) done.then(openSheet, openSheet);
        else openSheet();
        done.then(
            () => feedback(button, 'Copied', 'check', true),
            () => feedback(button, 'Failed', 'alert', false)
        );
        return done;
    }

    // ---- panel ----------------------------------------------------------

    const PANEL_ID = '__cmc_panel';

    function tokenCell(r) {
        const wrap = el('div', 'token');
        if (r.avatar) {
            const img = document.createElement('img');
            img.src = r.avatar;
            img.alt = '';
            img.onerror = () => img.remove();
            wrap.appendChild(img);
        }
        const names = el('div', 'names');
        names.appendChild(el('div', 'sym', r.symbol || '—'));
        names.appendChild(el('div', 'sub',
            (r.slug || '') + (r.id != null ? '  #' + r.id : '')));
        wrap.appendChild(names);
        return wrap;
    }

    function tableOf(rows) {
        const table = document.createElement('table');

        const thead = document.createElement('thead');
        const headRow = document.createElement('tr');
        ['Token', 'Chain', 'Contract', ''].forEach(label => {
            const th = document.createElement('th');
            th.textContent = label;
            headRow.appendChild(th);
        });
        thead.appendChild(headRow);
        table.appendChild(thead);

        const tbody = document.createElement('tbody');
        rows.forEach(r => {
            const tr = document.createElement('tr');

            const token = document.createElement('td');
            token.appendChild(tokenCell(r));
            tr.appendChild(token);

            const chain = document.createElement('td');
            chain.className = 'dim';
            chain.appendChild(el('span', 'clip', r.platformName || '—'));
            tr.appendChild(chain);

            const contract = document.createElement('td');
            const code = el('span', 'clip', r.tokenAddress || '—');
            // the cell truncates, so the full value has to be reachable
            code.title = r.tokenAddress || '';
            contract.appendChild(code);
            tr.appendChild(contract);

            const act = document.createElement('td');
            act.className = 'act';
            act.appendChild(copyIconBtn('Copy this row as TSV', () => tsvOf(r)));
            tr.appendChild(act);

            tbody.appendChild(tr);
        });
        table.appendChild(tbody);
        return table;
    }

    // force: open the panel even with nothing found, as feedback that a
    // hand-pasted script installed. Installed, it waits until it has
    // something to show rather than sitting on every page.
    function render(force) {
        const onPageRows = onPage();
        const rows = applyQuery(onPageRows);

        const existing = document.getElementById(PANEL_ID);
        let ui = existing && existing.__ui;
        if (!ui) {
            if (!onPageRows.length && !force) return;
            ui = shell(PANEL_ID, 470);
        }
        const panel = ui.panel;
        panel.textContent = '';

        const state = filterState();
        const total = listAll().length;

        const head = header(ui, 'CMC Tokens', rows.length, [
            iconBtn(state.active ? 'filter' : 'layers',
                state.active ? 'This coin only — click to show every coin found'
                    : 'Every coin found — click to filter to this page',
                () => { onlyCurrent = !onlyCurrent; render(true); },
                state.active ? 'on' : ''),
            iconBtn('refresh', 'Scan the page again', () => scan()),
            iconBtn(minimized ? 'plus' : 'minus', minimized ? 'Expand' : 'Collapse',
                () => { minimized = !minimized; render(true); }),
            iconBtn('x', 'Close', () => ui.host.remove())
        ]);
        panel.appendChild(head);
        const headCount = head.querySelector('.count');

        if (minimized) return;

        const strip = el('div', 'strip');
        strip.appendChild(icon(state.active ? 'filter' : 'layers', 12));
        if (!state.slug) {
            strip.appendChild(el('span', null, 'not a coin page — every coin found'));
        } else if (!onlyCurrent) {
            strip.appendChild(el('span', null, 'every coin found'));
        } else if (state.matched) {
            strip.appendChild(el('span', 'k', state.slug));
            if (total - state.matched) {
                strip.appendChild(el('span', 'faint', '· ' + (total - state.matched) + ' hidden'));
            }
        } else {
            strip.appendChild(el('span', null, 'no match for "' + state.slug + '" — showing all'));
        }
        panel.appendChild(strip);

        const body = el('div', 'body');

        // Typing repaints the rows only. Rebuilding the whole panel would
        // recreate the input and take the caret with it on every keystroke.
        const search = searchBox(
            { query: query, placeholder: 'filter…  sol  ·  chain:solana  ·  sym:btc' },
            value => {
                query = value;
                const shown = applyQuery(onPage());
                paint(body, shown);
                headCount.textContent = String(shown.length);
                search.update(shown.length, onPageRows.length);
            });
        panel.appendChild(search.el);
        panel.appendChild(body);

        paint(body, rows);
        search.update(rows.length, onPageRows.length);

        const foot = el('div', 'foot');

        const copyBar = el('div', 'bar');
        copyBar.appendChild(copyBtn('TSV', 'sheet',
            'Tab-separated, one row per contract:\n' + COLUMNS.join(' / '),
            () => visible().map(tsvOf).join('\n')));
        copyBar.appendChild(copyBtn('JSON', 'braces', 'Every row shown, as JSON',
            () => JSON.stringify(visible().map(r => JSON.parse(jsonOf(r))), null, 2)));
        foot.appendChild(copyBar);

        const goBar = el('div', 'bar');
        goBar.appendChild(textBtn('Copy + Open Sheet', 'link',
            'Copies every row shown, then opens the sheet — just paste:\n'
            + (CONFIG.sheetUrl || '(no sheet URL set)'),
            b => copyAndOpenSheet(visible().map(tsvOf).join('\n'), b), 'primary'));
        goBar.appendChild(textBtn('', 'trash', 'Clear everything captured',
            () => { clearAll(); query = ''; render(true); }, 'narrow'));
        foot.appendChild(goBar);

        panel.appendChild(foot);
        panel.appendChild(el('div', 'hint', 'TSV columns — ' + COLUMNS.join(' · ')));
    }

    // The copy buttons follow the filter: what is on screen is what is copied.
    function visible() {
        return applyQuery(onPage());
    }

    function paint(body, rows) {
        body.textContent = '';
        if (!rows.length) {
            body.appendChild(emptyState(query ? 'search' : 'scan', query
                ? 'Nothing matches that filter.'
                : 'Nothing found in the page source. Open a coin page, then rescan.'));
            return;
        }
        body.appendChild(tableOf(rows));
    }

    function show() {
        const all = list();
        render(true);
        if (!all.length) {
            console.warn('[cmc] nothing found - open a coin page and run __cmc.scan(), '
                + 'or __cmc.probe() to see what the page does contain');
            return;
        }
        console.log('%c CMC TOKENS (' + all.length + ') ',
            'background:#000;color:#fff;font-weight:bold;padding:2px 6px');
        console.table(all.map(r => Object.fromEntries(
            FIELDS.map(([label, key]) => [label, r[key]]))));
    }

    // When nothing is found, this says which keys the page does carry, so the
    // extraction can be pointed at the right ones rather than guessed at again.
    function probe() {
        const names = ADDRESS_KEYS.concat(PLATFORM_ID_KEYS, PLATFORM_NAME_KEYS,
            ['symbol', 'avatar', 'slug', 'address', 'platform', 'cryptoId']);
        const text = [...document.querySelectorAll('script')]
            .filter(s => !s.src).map(s => s.textContent || '').join('\n');
        const report = {};
        names.forEach(n => {
            report[n] = { plain: (text.split('"' + n + '"').length - 1),
                escaped: (text.split('\\"' + n + '\\"').length - 1) };
        });
        console.log('inline script text: ' + text.length + ' chars');
        console.table(report);
        console.log('__NEXT_DATA__ present:', !!window.__NEXT_DATA__,
            '  __next_f present:', Array.isArray(self.__next_f));
        return report;
    }

    // ---- lifecycle ------------------------------------------------------
    // Nothing harvests until Scan is pressed. The page stays clean on load.

    const queueScan = () => { clearTimeout(timer); timer = setTimeout(scan, 400); };

    function onNav() {
        // do not harvest on SPA navigation — Scan / Rescan is the only way in
        if (document.getElementById(PANEL_ID)) render(false);
    }
    const origPush = history.pushState;
    const origReplace = history.replaceState;
    let historyHooked = false;
    let observer = null;

    function armListeners() {
        if (!historyHooked) {
            historyHooked = true;
            history.pushState = function (...a) { const r = origPush.apply(this, a); onNav(); return r; };
            history.replaceState = function (...a) { const r = origReplace.apply(this, a); onNav(); return r; };
            window.addEventListener('popstate', onNav);
        }
        if (observer) return;
        // App Router streams its payload in after first paint. Only watch
        // after the user asked for a Scan, so a too-early click still lands.
        try {
            observer = new MutationObserver(records => {
                for (const rec of records) {
                    for (const n of rec.addedNodes) {
                        if (n.tagName === 'SCRIPT' && !n.src) { queueScan(); return; }
                    }
                }
            });
            observer.observe(document.documentElement, { childList: true, subtree: true });
        } catch (e) { /* the Rescan button still works */ }
    }

    // The popup's Show Panel button and any settings change arrive as plain
    // DOM events, the only channel the two worlds share.
    const onStoredConfig = () => {
        applyStoredConfig();
        if (document.getElementById('__cmc_panel')) render(false);
    };
    function requestScan() {
        armListeners();
        const n = scan();
        render(true);
        if (n) show();
        else console.log('%c[cmc] scanned%c  nothing yet — open a coin page, then Scan again',
            'color:#000;font-weight:bold', 'color:#666');
        return n;
    }
    const onShowRequest = () => { requestScan(); };
    document.addEventListener('xcap:config', onStoredConfig);
    document.addEventListener('xcap:show', onShowRequest);

    function uninstall() {
        document.removeEventListener('xcap:config', onStoredConfig);
        document.removeEventListener('xcap:show', onShowRequest);
        clearTimeout(timer);
        if (observer) observer.disconnect();
        history.pushState = origPush;
        history.replaceState = origReplace;
        window.removeEventListener('popstate', onNav);
        const p = document.getElementById('__cmc_panel');
        if (p) p.remove();
        delete window.__cmc;
    }

    window.__cmc = {
        scan: () => { armListeners(); return scan(); }, show, probe, uninstall, openSheet,
        list,
        all: listAll,
        showAll: () => { onlyCurrent = false; show(); },
        showCurrent: () => { onlyCurrent = true; show(); },
        pageSlug,
        columns: () => COLUMNS.slice(),
        config: CONFIG,
        copyAndOpen: () => copyAndOpenSheet(list().map(tsvOf).join('\n')),
        // every object carrying the key, exactly as found - for checking what
        // the page really returned when a field comes out blank
        hits: () => rawHits.slice(),
        sources: () => sources.slice(),
        json: () => JSON.stringify(list().map(r => JSON.parse(jsonOf(r))), null, 2),
        sheets: () => list().map(tsvOf).join('\n'),
        tsv: () => list().map(tsvOf).join('\n'),
        reset: () => { clearAll(); render(true); }
    };

    const AUTO = typeof GM_info !== 'undefined'
        || (typeof __XCAP_EXTENSION !== 'undefined' && __XCAP_EXTENSION);
    // Installed: wait for Scan (popup button or __cmc.scan).
    // Pasted into the console: run once so the paste is visible feedback.
    if (!AUTO) requestScan();
    else console.log('%c[cmc] ready%c  press Scan in the toolbar popup',
        'color:#000;font-weight:bold', 'color:#666');
})();
